system/apps/core/urls.py
from django.urls import path
#
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post'),
    path('post/edit/<pk>/<action>/', views.PostEditView.as_view(), name='edit'),
    path('posts/', views.PostListView.as_view(), name='posts'),
    path('favorites/', views.FavoriteListView.as_view(), name='favorites'),
    
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    #
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

system/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    # Urls Locals
    path('admin/', admin.site.urls),
    #
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

system/apps/core/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.models import User
#
from tinymce import models as tinymce_models
from easy_thumbnails.fields import ThumbnailerImageField

class Category(models.Model):
    title = models.CharField('Titulo', max_length=50)    
    
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categorys"
                
    def __str__(self):
        return self.title
    
    
class Post(models.Model):
    title = models.CharField('Titulo', max_length=200)    
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoria')
    image = ThumbnailerImageField(verbose_name='Imagen', upload_to='images', blank=True)
    content = tinymce_models.HTMLField(verbose_name='Contenido')
    description = models.TextField(null=True, blank=True, verbose_name='Descripcion')
    created = models.DateTimeField('Creacion', default=timezone.now)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("core:post", kwargs={"pk": self.pk})
    
    
class Favorite(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_favorites')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_favorites')

    class Meta:
        verbose_name = "Favorite"
        verbose_name_plural = "Favorites"
        unique_together = ('post', 'user')

system/apps/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

system/apps/core/views.py
from typing import Any, Dict
from django.urls import reverse_lazy
from django.contrib.auth import login, logout
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, RedirectView, FormView, DetailView, ListView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
# 
from .models import Post, Category, Favorite


class IndexView(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_first"] =  Post.objects.first()
        context["posts_1"] =  Post.objects.all()[0:3]
        context["posts_2"] =  Post.objects.all()[3:6]
        context["posts_recents"] =  Post.objects.all()[0:6]
        return context
    

class PostDetailView(DetailView):
    model = Post
    template_name = "detail.html"
    context_object_name = "post"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all()
        context["categories"] = Category.objects.all()
        if self.request.user.is_authenticated:
            context["favorite"] = Favorite.objects.filter(user=self.request.user, post=self.object).exists()
        else:
            context["favorite"] = False
        return context
    

class PostListView(ListView):
    model = Post
    template_name = "list.html"
    context_object_name = "posts"   
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()        
        return context


class FavoriteListView(LoginRequiredMixin, ListView):
    model = Favorite
    template_name = "favorites.html"
    context_object_name = "favorites"   
    
    def get_queryset(self):
        return Favorite.objects.filter(user=self.request.user)
    
        
class PostEditView(RedirectView):
    url = reverse_lazy('core:index')
    
    def get_redirect_url(self, *args, **kwargs):
        self.url = self.request.META['HTTP_REFERER']
        if self.request.user.is_authenticated:
            post = get_object_or_404(Post, pk=kwargs['pk'])
            if kwargs['action'] == 'add':
                Favorite.objects.create(user=self.request.user, post=post)
            if kwargs['action'] == 'delete':
                Favorite.objects.filter(user=self.request.user, post=post).delete()
            
        return super().get_redirect_url(*args, **kwargs)
     
    
class AboutView(TemplateView):
    template_name = "about.html"


class ContactView(TemplateView):
    template_name = "contact.html"
    
    
class LoginView(FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('core:index')   
    template_name = "login.html" 
    
    def get_initial(self):
        initial = super(LoginView, self).get_initial()
        initial.update({'username': "demo"})
        return initial
        
    def form_valid(self, form):
        if form.is_valid():
            login(self.request, form.get_user())
        return super().form_valid(form)
        
    
class LogoutView(RedirectView):
    url = reverse_lazy('core:index')
    
    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

system/templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<main id="main">
    <section>
      <div class="container" data-aos="fade-up">
        <div class="row">
          <div class="col-lg-12 text-center mb-5">
            <h1 class="page-title">Acerca de Nosotros</h1>
          </div>
        </div>

        <div class="row mb-5">


          <div class="d-md-flex post-entry-2 half mt-5">
            <a href="#" class="me-4 thumbnail order-2">
              <img src="{% static 'assets/img/post-landscape-1.jpg' %}" alt="" class="img-fluid">
            </a>
            <div class="pe-md-5 mt-4 mt-md-0">
              <div class="post-meta mt-4">Mission &amp; Vision</div>
              <h2 class="mb-4 display-4">Mission &amp; Vision</h2>

              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
              <p>Fugit eaque illum blanditiis, quo exercitationem maiores autem laudantium unde excepturi dolores quasi eos vero harum ipsa quam laborum illo aut facere voluptates aliquam adipisci sapiente beatae ullam. Tempora culpa iusto illum accusantium cum hic quisquam dolor placeat officiis eligendi.</p>
            </div>
          </div>

        </div>

      </div>
    </section>


    <section>
      <div class="container" data-aos="fade-up">
        <div class="row">
          <div class="col-12 text-center mb-5">
            <div class="row justify-content-center">
              <div class="col-lg-6">
                <h2 class="display-4">Nuestro Equipo</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil sint sed, fugit distinctio ad eius itaque deserunt doloribus harum excepturi laudantium sit officiis et eaque blanditiis. Dolore natus excepturi recusandae.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 text-center mb-5">
            <img src="{% static 'assets/img/person-1.jpg' %}" alt="" class="img-fluid rounded-circle w-50 mb-4">
            <span class="d-block mb-3 text-uppercase">Integrante</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          </div>
          <div class="col-lg-4 text-center mb-5">
            <img src="{% static 'assets/img/person-2.jpg' %}" alt="" class="img-fluid rounded-circle w-50 mb-4">
            <span class="d-block mb-3 text-uppercase">Integrante</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          </div>
          <div class="col-lg-4 text-center mb-5">
            <img src="{% static 'assets/img/person-3.jpg' %}" alt="" class="img-fluid rounded-circle w-50 mb-4">
            <span class="d-block mb-3 text-uppercase">Integrante</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          </div>
          <div class="col-lg-4 text-center mb-5">
            <img src="{% static 'assets/img/person-4.jpg' %}" alt="" class="img-fluid rounded-circle w-50 mb-4">
            <span class="d-block mb-3 text-uppercase">Integrante</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          </div>
          <div class="col-lg-4 text-center mb-5">
            <img src="{% static 'assets/img/person-5.jpg' %}" alt="" class="img-fluid rounded-circle w-50 mb-4">
            <span class="d-block mb-3 text-uppercase">Integrante</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          </div>
          <div class="col-lg-4 text-center mb-5">
            <img src="{% static 'assets/img/person-6.jpg' %}" alt="" class="img-fluid rounded-circle w-50 mb-4">
            <span class="d-block mb-3 text-uppercase">Integrante</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          </div>
        </div>
      </div>
    </section>

  </main><!-- End #main -->
    
{% endblock content %}

system/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Yachaykusun: Web de Aprendizaje</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS Files -->
  <link href="{% static 'assets/css/variables.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: ZenBlog
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/zenblog-bootstrap-blog-template/
  * Author: BootstrapMade.com
  * License: https:///bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

	<!-- ======= Header ======= -->
	{% include "includes/header.html" %}
	<!-- ======= Header ======= -->

	{% block content %}		
	{% endblock content %}


	<!-- Footer -->
	{% include 'includes/footer.html' %}

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <!-- <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script> -->

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

system/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  <main id="main">
    <section id="contact" class="contact mb-5">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-12 text-center mb-5">
            <h1 class="page-title">Contact us</h1>
          </div>
        </div>

        <div class="row gy-4">

          <div class="col-md-4">
            <div class="info-item">
              <i class="bi bi-geo-alt"></i>
              <h3>Address</h3>
              <address>A108 Adam Street, NY 535022, USA</address>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-4">
            <div class="info-item info-item-borders">
              <i class="bi bi-phone"></i>
              <h3>Phone Number</h3>
              <p><a href="tel:+155895548855">+1 5589 55488 55</a></p>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-4">
            <div class="info-item">
              <i class="bi bi-envelope"></i>
              <h3>Email</h3>
              <p><a href="mailto:info@example.com">info@example.com</a></p>
            </div>
          </div><!-- End Info Item -->

        </div>

        <div class="form mt-5">
          <form action="forms/contact.php" method="post" role="form" class="php-email-form">
            <div class="row">
              <div class="form-group col-md-6">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
            </div>
            <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>
        </div><!-- End Contact Form -->

      </div>
    </section>

  </main><!-- End #main -->
    
{% endblock content %}

system/templates/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<main id="main">

  <section class="single-post-content">
    <div class="container">
      <div class="row">
        <div class="col-md-9 post-content" data-aos="fade-up">

          <!-- ======= Single Post Content ======= -->
          <div class="single-post">
            <div class="post-meta"><span class="date">{{ post.category }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.created }}</span></div>

            {% if user.is_authenticated %}

              {% if favorite %}
              <a href="{% url 'core:edit' post.id 'delete' %}" class="btn btn-danger">
                <span class="bi-dash-circle"></span> Eliminar de Favoritos
              </a>
              {% else %}
              <a href="{% url 'core:edit' post.id 'add' %}" class="btn btn-success">
                <span class="bi-suit-heart"></span> Añadir a Favoritos
              </a>
              {% endif %}
            {% endif %}

            <h1 class="mb-5">{{ post.title }}</h1>

            {% if post.description %}
            <p>
              {{ post.description }}
            </p>
            {% else %}
            <p><span class="firstcharacter">L</span>orem ipsum dolor sit, amet consectetur adipisicing elit. Ratione officia sed, suscipit distinctio, numquam omnis quo fuga ipsam quis inventore voluptatum recusandae culpa, unde doloribus saepe labore alias voluptate expedita? Dicta delectus beatae explicabo odio voluptatibus quas, saepe qui aperiam autem obcaecati, illo et! Incidunt voluptas culpa neque repellat sint, accusamus beatae, cumque autem tempore quisquam quam eligendi harum debitis.</p>

            {% endif %}

            {% if post.image %}
            <figure class="my-4">
              <img src="{{ post.image.url }}" alt="" class="img-fluid" width="80%">
            </figure>
              
            {% endif %}

            {{ post.content | safe }}

          </div><!-- End Single Post Content -->

          <!-- ======= Comments ======= -->
          <div class="comments">
            <h5 class="comment-title py-4">1 Comentarios</h5>
            <div class="comment d-flex mb-2">
              <div class="flex-shrink-0">
                <div class="avatar avatar-sm rounded-circle">
                  <img class="avatar-img" src="{% static 'assets/img/person-2.jpg' %}" alt="" class="img-fluid">
                </div>
              </div>
              <div class="flex-shrink-1 ms-2 ms-sm-3">
                <div class="comment-meta d-flex">
                  <h6 class="me-2">Santiago Roberts</h6>
                  <span class="text-muted">4d</span>
                </div>
                <div class="comment-body">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto laborum in corrupti dolorum, quas delectus nobis porro accusantium molestias sequi.
                </div>
              </div>
            </div>
          </div><!-- End Comments -->

          <!-- ======= Comments Form ======= -->
          <div class="row justify-content-center mt-5">

            <div class="col-lg-12">
              <h5 class="comment-title">Nuevo Comentario</h5>
              <div class="row">
                <div class="col-lg-6 mb-3">
                  <label for="comment-name">Name</label>
                  <input type="text" class="form-control" id="comment-name" placeholder="Enter your name">
                </div>
                <div class="col-lg-6 mb-3">
                  <label for="comment-email">Email</label>
                  <input type="text" class="form-control" id="comment-email" placeholder="Enter your email">
                </div>
                <div class="col-12 mb-3">
                  <label for="comment-message">Message</label>

                  <textarea class="form-control" id="comment-message" placeholder="Enter your name" cols="30" rows="10"></textarea>
                </div>
                <div class="col-12">
                  <input type="submit" class="btn btn-primary" value="Publicar Comentario">
                </div>
              </div>
            </div>
          </div><!-- End Comments Form -->

        </div>
        <div class="col-md-3">
          <!-- ======= Sidebar ======= -->
          <div class="aside-block">

            <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Popular</button>
              </li>
            </ul>

            <div class="tab-content" id="pills-tabContent">

              <!-- Popular -->
              <div class="tab-pane fade show active" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">

                
                {% for post in posts %}

                <div class="post-entry-1 border-bottom">
                  <div class="post-meta"><span class="date">{{ post.category }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.created }}</span></div>
                  <h2 class="mb-2"><a href="{% url 'core:post' post.pk %}">{{ post.title }}</a></h2>
                  <!-- <span class="author mb-3 d-block">Jenny Wilson</span> -->
                </div>
                  
                {% endfor %}
              
              </div> <!-- End Popular -->


            </div>
          </div>

          <div class="aside-block">
            <h3 class="aside-title">Video</h3>
            <div class="video-post">
              <a href="https://www.youtube.com/watch?v=KHwulWMKazU" class="glightbox link-video">
                <span class="bi-play-fill"></span>
                <img src="{% static 'assets/img/post-landscape-5.jpg' %}" alt="" class="img-fluid">
              </a>
            </div>
          </div><!-- End Video -->

          <div class="aside-block">
            <h3 class="aside-title">Categories</h3>
            <ul class="aside-links list-unstyled">
              
              {% for category in categories %}

              <li><a href="#"><i class="bi bi-chevron-right"></i> {{ category }}</a></li>
                
              {% endfor %}
                
            </ul>
          </div><!-- End Categories -->


        </div>
      </div>
    </div>
  </section>
</main><!-- End #main -->
    
{% endblock content %}

system/templates/favorites.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  <main id="main">

    <!-- ======= Search Results ======= -->
    <section id="search-result" class="search-result">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h3 class="category-title">Favoritos</h3>
            
            {% for favorite in favorites %}   
            
            {% with favorite.post as post %}
                                                    
            <div class="d-md-flex favorite-entry-2 small-img mb-2">
              <a href="{% url 'core:post' post.pk %}" class="me-4 thumbnail">
                {% if post.image %}
                <img src="{{ post.image.url }}" alt="" class="img-fluid">
                {% else %}
                <img src="{% static 'assets/img/post-landscape-2.jpg' %}" alt="" class="img-fluid">                  
                {% endif %}
              </a>
              <div>
                <div class="favorite-meta"><span class="date">{{ post.category }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.created }}</span></div>
                <h3><a href="{% url 'core:post' post.pk %}">{{post.title}}</a></h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio placeat exercitationem magni voluptates dolore. Tenetur fugiat voluptates quas.</p>
                <div class="d-flex align-items-center author">
                  <div class="photo"><img src="{% static 'assets/img/person-3.jpg' %}" alt="" class="img-fluid"></div>
                  <div class="name">
                    <h3 class="m-0 p-0">Juan Cristhian</h3>
                  </div>
                </div>
                <a href="{% url 'core:edit' post.id 'delete' %}" class="btn btn-sm btn-danger mt-2">
                  <span class="bi-dash-circle"></span> Eliminar de Favoritos
                </a>
              </div>
            </div>
            {% endwith %}
            {% empty %}
            <div class="alert alert-danger" role="alert">
              Ningun favorito registrado
            </div>
            {% endfor %}

            <!-- Paging -->
            <div class="text-start py-4">
              <div class="custom-pagination">
                <a href="#" class="prev">Anterior</a>
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
                <a href="#" class="next">Siguiente</a>
              </div>
            </div><!-- End Paging -->

          </div>


        </div>
      </div>
    </section> <!-- End Search Result -->

  </main><!-- End #main -->


{% endblock content %}

system/templates/includes/header.html
{% load static %}

{% url 'core:index' as index %}
{% url 'core:posts' as posts %}
{% url 'core:favorites' as favorites %}
{% url 'core:about' as about %}
{% url 'core:contact' as contact %}
{% url 'core:logout' as logout %}
{% url 'core:login' as login %}
    


<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center fixed-top">
<div class="container-fluid container-xl d-flex align-items-center justify-content-between">

    <a href="index.html" class="logo d-flex align-items-center">
    <!-- Uncomment the line below if you also wish to use an image logo -->
    <!-- <img src="{% static 'assets/img/logo.png' %}" alt=""> -->
    <h1>Yachaykusun</h1>
    </a>

    <nav id="navbar" class="navbar">
    <ul>
        <li><a href="{{ index }}">Inicio</a></li>
        <li><a href="{{ posts }}">Publicaciones</a></li>
        <li><a href="{{ about }}">Acerca de</a></li>
        <li><a href="{{ contact }}">Contacto</a></li>

        {% if user.is_authenticated %}

        <li><a href="{{ favorites }}">
            Mis favoritos
            </a>
        </li>
        <li><a href="{{ logout }}">
            <span class="bi-door-closed"></span>
            Cerrar Sesion
            </a>
        </li>

        {% else %}

        <li><a href="{{ login }}">
            <span class="bi-shield-exclamation"></span>
             Ingresar
            </a>
        </li>
          
        {% endif %}
    </ul>
    </nav><!-- .navbar -->

    <div class="position-relative">
    <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
    <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
    <a href="#" class="mx-2"><span class="bi-instagram"></span></a>

    <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
    <i class="bi bi-list mobile-nav-toggle"></i>

    <!-- ======= Search Form ======= -->
    <div class="search-form-wrap js-search-form-wrap">
        <form action="search-result.html" class="search-form">
        <span class="icon bi-search"></span>
        <input type="text" placeholder="Search" class="form-control">
        <button class="btn js-search-close"><span class="bi-x"></span></button>
        </form>
    </div><!-- End Search Form -->

    </div>

</div>

</header>
<!-- End Header -->

system/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  <main id="main">
    <section id="contact" class="contact mb-5">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-12 text-center mb-5">
            <h1 class="page-title">Ingresar</h1>
            <h5>(Accesos de prueba: Usuario/Cotraseña => demo/demo)</h5>
          </div>
        </div>

        <div class="form mt-2">
          <form method="post" class="php-email-form">
            {% csrf_token %}
            <div class="row mb-2">
              {{ form }}
            </div>          

            <div class="text-center"><button type="submit">Ingresar</button></div>
          </form>
        </div><!-- End Contact Form -->

      </div>
    </section>

  </main><!-- End #main -->
    
{% endblock content %}